### ISSUE TITLE
Can't call API methods passing a string to the plugin

### ISSUE THREAD

**Issue by andrefgneves** [gfranko/jqfactory#1]
Hi,

I can't get API methods to run when passing the method name as a string to the plugin. Using the data approach works though.

Here's a pen so you can see what I mean: http://codepen.io/andrefgneves/pen/KGhbk

Am I doing something wrong?

Thanks.

**Comment by gfranko** [comment]
Thank you for reporting this!  You can grab the latest code here: https://github.com/gfranko/jqfactory/tree/master/src and everything should work for you.  Let me know if you find anything else!

**Comment by andrefgneves** [comment]
Awesome, thanks.

**Comment by gfranko** [comment]
@andrefgneves How are you like jqfactory so far?  Anything you think could be improved?

**Comment by andrefgneves** [comment]
Actually, it would be nice if calling API methods by passing a string returned the method's return value (if any). It seems to always return the $callingElement. It's nice for chainability, but I'd argue most times the method's return value is what's desired. Should I create a new issue?

Other than that, I'm loving it. Great job :)

**Comment by gfranko** [comment]
I think that most plugin users expect it to be chainable and returning the calling element would break a common convention.  Still mulling it over tho.

**Comment by andrefgneves** [comment]
So, if I have something like:

``` javascript
$.jqfactory('seven.awesomeness', {
    value: function () {
        return 'a lot';
    }
});
```

and do:

``` javascript
var awesomenessValue = $('.something').awesomeness('value');
```

I'd expect to get 'a lot' and not the $callingElement as it seems to always return now. But that's just me :)
Right now we need to do:

``` javascript
var awesomenessValue = $('.something').data('sevenAwesomeness').value();
```

which I have no problem with. But I if I go with passing strings to the plugin, I want code style to be consistent.
Just my 2 cents, I'm fine if you decide to keep it as is.

Thanks.

**Comment by gfranko** [comment]
I definitely understand where you're coming from, but for now, I am going to keep it as is. PR's are always welcome though =)
