### ISSUE TITLE
Regarding jqfactory usage - Not an issue

### ISSUE THREAD

**Issue by settysreekanth** [gfranko/jqfactory#5]
I dont see any update since 1 year - is jqfactory still being used or is it an old practice to use jqfactory? whats the new way if available?

**Comment by gfranko** [comment]
I think a lot of people have moved away from jquery and are using other frameworks (e.g. React).  But in terms of creating jQuery plugins, this is a good solution.

**Comment by settysreekanth** [comment]
@gfranko Thank you for your reply.
